[package]
name = "spaceapi"
version = "0.1.0"
repository = "https://github.com/coredump-ch/spaceapi-rs/"
license = "MIT"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
]
description = "Space API types and serialization/deserialization."
readme = "README.md"
keywords = ["spaceapi", "hackerspaces", "status", "api"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE.txt",
    "AUTHORS.md",
]

[dependencies]
rustc-serialize = "^0.3"
log = "^0.3"
